# Generated by Django 3.2.7 on 2021-09-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20210909_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('cv_text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='project')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cv',
                'verbose_name_plural': 'Cvs',
                'ordering': ('title_name',),
            },
        ),
    ]
