# Generated by Django 3.2.7 on 2021-09-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_alter_cv_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='on_main_page',
            field=models.BooleanField(default=False),
        ),
    ]
