# Generated by Django 3.2.7 on 2021-09-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_cv_on_main_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='mail_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('tel', models.TextField(max_length=200)),
                ('web', models.TextField(max_length=200)),
                ('info', models.TextField()),
            ],
        ),
    ]
