# Generated by Django 3.2.7 on 2021-09-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_mail_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail_me',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mail_me',
            name='mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='mail_me',
            name='tel',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mail_me',
            name='web',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
