# Generated by Django 3.2.7 on 2021-09-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_auto_20210910_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(blank=True, max_length=254)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('tel', models.TextField(blank=True, max_length=200)),
                ('web', models.TextField(blank=True, max_length=200)),
                ('info', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'mail_my',
                'verbose_name_plural': 'mail_my',
                'ordering': ('mail',),
            },
        ),
        migrations.DeleteModel(
            name='mail_me',
        ),
    ]
