# Generated by Django 3.2.7 on 2021-09-10 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_auto_20210910_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='my_mail',
            options={'ordering': ('mail',), 'verbose_name': 'My_mail', 'verbose_name_plural': 'My_mails'},
        ),
    ]
