# Generated by Django 3.2.7 on 2021-09-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_project_phase_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.CharField(default=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='phase_project',
            field=models.CharField(max_length=250),
        ),
    ]
