# Generated by Django 3.2.7 on 2021-09-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_auto_20210913_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github',
            field=models.CharField(default='http://github.com', max_length=250),
        ),
    ]
