# Generated by Django 3.2.7 on 2021-09-13 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0012_alter_project_github'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='github',
        ),
    ]
