# Generated by Django 3.2.7 on 2021-09-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0013_remove_project_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='git_page',
            field=models.TextField(default='https://github.com'),
        ),
    ]
